server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: eureka-service-registry

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: qa

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: uat

---
spring:
  config:
    activate:
      on-profile: prod


